### ISSUE TITLE
Add ArgumentParser to SAGE

### ISSUE THREAD

**Issue by jzelenjak** [tudelft-cda-lab/SAGE#25]
## Description

Currently, parsing of the input arguments is happening manually, which is a bit cumbersome.

![image](https://github.com/tudelft-cda-lab/SAGE/assets/45541174/8e91e052-dbd1-4492-ae17-b3cdb3dd1a3a)

Furthermore, another optional parameter has to be added for the dataset name. This is needed because some if-checks in the code are CPTC-specific (see issue #24).

## Proposed solution

1. Replace the manual parsing with `ArgumentParser` (similar to [SECLEDS](https://github.com/tudelft-cda-lab/SECLEDS))
2. Add one more option: `dataset_name` (options = {"cptc", "other"}, default value = "other")
3. Optionally, add another optional parameter to not remove the dot files
4. Update the `docker` branch accordingly (only the new options have to be added to the `script.sh` and `input.ini` files, no other changes are necessary, i.e. the `input.ini` file remains only on the `docker` branch, `spdfa-config.ini` remains only on the `main` branch, argument parsing remains in the `sage.py`, with the exception that default values of optional parameters will be added to the `script.sh` file).
5. Update the documentation for the `main` and `docker` branches

**Comment by azqanadeem** [comment]
About point 3: Update the DOCKER flag value with the one parsed from the CMD arguments. The Default value of True(?) remains.
