### ISSUE TITLE
Structure the filtering part when parsing the alerts

### ISSUE THREAD

**Issue by jzelenjak** [tudelft-cda-lab/SAGE#26]
## Description

Sometimes, there are attackers which generate 99% of the alerts, which in the code are called `bad_ip` and are skipped. Furthermore, there are alerts that occur way too often and could be filtered, if necessary (see below).

![image](https://github.com/tudelft-cda-lab/SAGE/assets/45541174/15ab9319-d676-47d6-92af-05007fcb1e92)
![image](https://github.com/tudelft-cda-lab/SAGE/assets/45541174/c595813b-72cd-4b90-8eeb-2e9fe5bdbf11)
![image](https://github.com/tudelft-cda-lab/SAGE/assets/45541174/4f4cfdcc-6146-4838-a704-34753ecd038e)

The `bad_ip` might be dataset-specific, and the checks for "Attempted Information Leak" and "Non Suspicious Traffic" might be needed only in case of `bad_ip`.

## Proposed Solution

1. Check bad IPs for CPTC/CCDC and decide on how to proceed
2. Check what happens if we remove the check for "Not Suspicious Traffic"? `_remove_duplicate` method checks for `NON_MALICIOUS` traffic, however the former is a SURICATA category, while the latter is part of the `MicroAttackStage` framework
3. Update the `_parse` function accordingly

**Comment by azqanadeem** [comment]
Also kinda links to #24
