### ISSUE TITLE
Why is there an error in the input script according to the sample-input.json you gave.

### ISSUE THREAD

**Issue by jiangdie666** [tudelft-cda-lab/SAGE#9]
![image](https://user-images.githubusercontent.com/72592733/211796516-189e3360-897d-454c-ba30-505fd871efc2.png)

**Comment by azqanadeem** [comment]
First, the example file only has 4 alerts, so it will not create any attack graph. This file is meant to give an idea of the required alert format.

Second, the error you get is because SAGE cannot find one of the files created by Flexfringe. Can you post what files have been created by Flexfringe? They should have the extension `.dot` and `.json`.

**Comment by jiangdie666** [comment]
Figure 1 shows my overall folder structure, with the 1 folder holding sample-input.json.
![V4{AO 01NNM9Z1CKTV V25W](https://user-images.githubusercontent.com/72592733/211801482-0224125a-6430-43e4-aca2-f463e1517997.png)

Figure 2 shows the internal structure of the FlexFringe folder created as per the requirements of the trick, all folders are copied and pasted from within FlexFringe, flexfringe is the compiled program.
![}Q09MN@6}WHWU9CVV2B{ 06](https://user-images.githubusercontent.com/72592733/211801508-f8b20616-ce8d-4888-a674-a89c6b0b8144.png)

Figure 3 is the output of sage.py inside the output, all without any changes.
![O8}LHF1GJ(D{67`AT3G_2BI](https://user-images.githubusercontent.com/72592733/211801544-be9b1a80-5856-492d-a374-8c659dc16299.png)

**Comment by azqanadeem** [comment]
That looks okay, and it seems that SAGE is able to find the Flexfringe executable. 

However, even before flexfringe runs, SAGE creates several output files, e.g., the histogram file (`png`), and a trace file (`.txt`) for flexfringe to learn from. I don't see them in your screenshots...

**Comment by jiangdie666** [comment]
This is what I get after executing the first screenshot that reports an error.
![image](https://user-images.githubusercontent.com/72592733/211804059-47185405-5c2c-4295-b772-546adc305aa7.png)

**Comment by azqanadeem** [comment]
Okay, that means SAGE works until the creation of the trace file, `first.txt` in your case. Can you show me what is contained in `first.txt`? 

My suspicion is that because there were only 4 alerts, there is insufficient data to learn anything by flexfringe, and hence it crashes.

**Comment by jiangdie666** [comment]
![image](https://user-images.githubusercontent.com/72592733/211804598-68361ee8-2806-4bbc-bfae-f27ab5c7a5de.png)
first 是我根据您代码编辑的{experiment_name} 名称。

**Comment by jiangdie666** [comment]
first is the name of the {experiment_name} that I edited from your code.
![image](https://user-images.githubusercontent.com/72592733/211805076-074bd076-42db-4939-9985-3c843cc36422.png)

**Comment by azqanadeem** [comment]
Yep, exactly. There are no traces to learn from. I suggest to download the alerts from one the of the CPTC-2018 teams from: `https://mirror.rit.edu/cptc/2018/t5/events/`. Download file `suricata_alert.json.gz`, unzip it. It should contain a `.json` file with alerts triggered by Team 5 of the CPTC-2018 competition. Then, you either need to convert the `.json` file into a list of json objects, or you can replace lines 1346-1348 of `sage.py` to:

``` 
unparsed_file = []
with open(fname, 'r') as f:
        for line in f:
            unparsed_file.append(json.loads(line))
```

Then, everything should work.

**Comment by jiangdie666** [comment]
![image](https://user-images.githubusercontent.com/72592733/211811571-27663b9e-ac7f-4822-ba42-f3d84d56393f.png)
Is this how the data format is handled?

**Comment by azqanadeem** [comment]
Yes, this new code snippet parses each line of the `.json` file, which is a json object. Then all the parsed json objects are appended in the `unparsed_file` list. 

Does it work? If not, then I'll push some changes to the code.

**Comment by jiangdie666** [comment]
![image](https://user-images.githubusercontent.com/72592733/211812609-1fd1ba16-f50f-4bb3-93f8-128feac034c9.png)
This is the result of his output.
![image](https://user-images.githubusercontent.com/72592733/211812702-3cfb4a85-f931-4c2b-afc8-9001e10014b5.png)
I think it's possible that I didn't handle the data format properly here.

**Comment by azqanadeem** [comment]
Okay, nevermind. I just tried it out. You don't need any changes to the code after all. 

Just pull a fresh copy of SAGE, update paths to `flexfringe.exe` (that you can now directly download from [https://github.com/tudelft-cda-lab/FlexFringe/releases](https://github.com/tudelft-cda-lab/FlexFringe/releases)) and the `.ini` file (from [https://github.com/tudelft-cda-lab/SAGE/blob/docker/spdfa-config.ini](https://github.com/tudelft-cda-lab/SAGE/blob/docker/spdfa-config.ini)). 

Then run on the T5 alerts you downloaded using this command: `python sage.py alerts/ first 1.0 150` (where `alerts/` contains your `.json` file)

Let me know if it works for you.

**Comment by jiangdie666** [comment]
After downloading the release version of frexfringe, I choose to operate on windows. Is the output below correct?
![image](https://user-images.githubusercontent.com/72592733/211819925-a01b503b-2099-4285-a544-ee0c707fb049.png)
But in sage.py, the rm delete operation will be executed at the end, but rm cannot be executed in windows, so this kind of error report is not important, right?

**Comment by azqanadeem** [comment]
Yes, correct! The `first.txt.png` file shows you the learnt s-pdfa model. The folder `firstAGs/` has all the extracted attack graphs, each in a `.dot`, `.png`, and `.svg` format.

The 'rm' error is not important.

**Comment by jiangdie666** [comment]
Thank you very much for your patience and guidance, for bothering you for so long with this little problem.v😊
